/**
 * 
 */
package Project;

import static org.junit.Assert.*;
import java.util.*;
import org.junit.After;

import org.junit.Before;
import org.junit.Test;

import java.io.*;
/**
 * @author lrdahlquist
 *
 */
public class UCTest {
	LoginUI loginUI;
	AdminUI adminUI;
	StudentUserInterface studentUI;
	DatabaseController dbc;
	Search_Controler sc;
	UserController uc;
	LogoutController lc;
	String uName = "case123";
	String pWord = "case123";
	String fName = "case";
	String lName = "tester";
	char type = 'u';
	char status= 'Y';
	Student caseTester = new Student(fName, lName, uName, pWord, type, status, null);
	private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
	
	@Before
	public void setup(){
		loginUI = new LoginUI();
		adminUI = new AdminUI();
		studentUI = new StudentUserInterface();
		dbc = new DatabaseController("lannp", "lannp","csci230");
		sc = new Search_Controler();
		uc = new UserController();
		lc = new LogoutController();
		Student caseTester = new Student(fName, lName, uName, pWord, type, status, null);
		dbc.addUser(uName, fName, lName, pWord, type, status);
	}
	
	@Before
	public void setUpStreams() {
	    System.setOut(new PrintStream(outContent));
	}
	
	@After
	public void cleanUpStreams() {
	    System.setOut(null);
	    dbc.removeSavedSchool(uName, "AUGSBURG");
	    dbc.deleteUser(uName);
	    dbc.deleteUser(lName);
	}
	
	/*
	 * tests login
	 */
	@Test
	public void testUC1(){
		assertTrue(loginUI.logon("case123", "case123", true));
	}
	
	/*
	 * viewProfile Test
	 */
	@Test
	public void testUC2(){
		String info = dbc.getUser(uName).toString();
		studentUI.viewProfile(uName);
		String output = outContent.toString().trim();
		assertTrue(output.equals(info));
	}
	
	/*
	 * Edit Profile Tests
	 * 	tests changing the first name
	 * 	tests changing the last name
	 * 	tests changing the password
	 */
	@Test
	public void testUC3_1editFirstName(){
		assertTrue(studentUI.editInfo(uName, "bob", lName, pWord, type, status));
		assertTrue(dbc.getUser(uName).getFirstName().equals("bob"));
	}
	@Test
	public void testUC3_2editLastName(){
		assertTrue(studentUI.editInfo(uName, fName, "theBuilder", pWord, type, status));
		assertTrue(dbc.getUser(uName).getLastName().equals("theBuilder"));
	}
	@Test
	public void testUC3_3editPassword(){
		assertTrue(studentUI.editInfo(uName, fName, lName, "case321", type, status));
		assertTrue(dbc.getUser(uName).getPassword().equals("case321"));
	}
	/*
	 * View Saved Schools Test
	 * 	checks the output stream to see if the
	 * 	output is actually matching what it should be
	 */
	@Test
	public void testUC4(){
		studentUI.viewSavedSchools(uName);
		String output = outContent.toString().trim();
		assertTrue(output.equals(dbc.getUser(uName).getSavedSchools().toString()));
	}
	
	/*
	 * Remove a school Test
	 * 	tests to see if a school is removed
	 */
	@Test
	public void testUC5(){
		studentUI.saveSchool(uName, "AUGSBURG");
		assertTrue(studentUI.removeSchool(uName, "AUGSBURG"));
		
	}
	
	/*
	 * Search for school test
	 * 	tests to see if the output generated by the tests
	 * 	actually matches what it should be
	 */
	@Test
	public void testUC6(){
		studentUI.searchSchool(null, null, null, null, 18000, 4000, 100, 0, 600, 300, 600, 300, 40000, 28000, 100, 60, 10000, 1000, 90, 30, 90, 30, 5, 1, 5, 1, 5, 1, null, null, null, null, null);
		String s = "ADELPHI"
				+ "\nAUGSBURG"
				+ "\nBARD"
				+ "\nBUTLER"
				+ "\nHOFSTRA"
				+ "\nMANHATTANVILLE COLLEGE"
				+ "\nMARIST COLLEGE"
				+ "\nPOLYTECHNIC INSTITUTE OF NEWYORK"
				+ "\nTRINITY COLLEGE";
		assertEquals(s, outContent.toString().trim());
	}
	/*
	 * View School Test
	 * 	tests to see if the outout generated by the viewSchool
	 * 	method called in student UI matches what it should be
	 */
	@Test
	public void testUC7(){
		studentUI.viewSchool("AUGSBURG");
		String output1 = outContent.toString().trim();
		System.setOut(null);
		assertTrue(output1.equals(dbc.getSchool("AUGSBURG").toString()));
	}
	
	/*
	 * Test Save School
	 * 	tests to see if a user can save a school
	 */
	@Test
	public void testUC8(){
		assertTrue(studentUI.saveSchool(uName, "AUGSBURG"));
	}
	
	/*
	 * Test Admin Login
	 * 	tests to see if logging in with admin credentials works
	 */
	@Test
	public void testUC9(){
		assertTrue(loginUI.logon("nadmin", "admin", true));
	}
	
	/*
	 * Test View Users
	 * 	makes sure the admin ui works correctly
	 */
	@Test
	public void testUC10(){
		dbc.deleteUser(uName);
		String expected = "Andrew,McIntyre,ajmac,password,u"
				+ "\nJohn,User,juser,user,u"
				+ "\nLynn,User,luser,user,u"
				+ "\nNoreen,Admin,nadmin,admin,a"
				+ "\nnick,floeder,nflo,nick,a";
		adminUI.viewusers();
		String output = outContent.toString().trim();
		assertTrue(output.equals(expected));
	}
	
	/*
	 * Test View User
	 * 	makes sure that the the adminUI performs 
	 * 	as expected
	 */
	@Test
	public void testUC11(){
		String expected  = "John,User,juser,user,u";
		adminUI.veiwUser("juser");
		String output1 = outContent.toString().trim();
		assertTrue(expected.equals(output1));
		
	}
	
	/*
	 * Edit User Tests
	 * 	tests changing the first name
	 * 	tests changing the last name
	 * 	tests changing the password
	 */
	@Test
	public void testUC12_1editFirstName(){
		assertTrue(adminUI.editUser(uName, "bob", lName, pWord, type, status));
		assertTrue(dbc.getUser(uName).getFirstName().equals("bob"));
	}
	@Test
	public void testUC12_2editLastName(){
		assertTrue(adminUI.editUser(uName, fName, "theBuilder", pWord, type, status));
		assertTrue(dbc.getUser(uName).getLastName().equals("theBuilder"));
	}
	@Test
	public void testUC12_3editPassword(){
		assertTrue(adminUI.editUser(uName, fName, lName, "case321", type, status));
		assertTrue(dbc.getUser(uName).getPassword().equals("case321"));
	}
	/*
	 * Add User Test
	 * 	checks to make sure you can add a user
	 * 	from the adminUI
	 */
	@Test
	public void testUC13(){
	    dbc.deleteUser(uName);
		assertTrue(adminUI.addUser(uName, fName, lName, pWord, type, status));
	}
	
	/*
	 * Deactivate User Test
	 * 	tests that you can successfully deactivate a user
	 */
	@Test
	public void testUC14(){
		assertTrue(adminUI.deactivateUser(uName));
	}
	
	/*
	 * View All Schools Test
	 * 	tests to see if the output generated by the admin UI
	 * 	matches what it should be
	 */
	@Test
	public void testUC15(){
		adminUI.viewSchools();
		String output1 = outContent.toString().trim();
		String schools ="ABILENE CHRISTIAN UNIVERSITY"
				+ "\nADELPHI"
				+ "\nAMERICAN UNIVERSITY OF BEIRUT"
				+ "\nARIZONA STATE"
				+ "\nAUBURN"
				+ "\nAUGSBURG"
				+ "\nBARD"
				+ "\nBARNARD"
				+ "\nBARUCH"
				+ "\nBAYLOR UNIVERSITY"
				+ "\nBENNINGTON"
				+ "\nBOSTON COLLEGE"
				+ "\nBOSTON UNIVERSITY"
				+ "\nBRANDEIS"
				+ "\nBROWN"
				+ "\nBRYN MAWR"
				+ "\nBUCKNELL"
				+ "\nBUTLER"
				+ "\nCAL TECH"
				+ "\nCARNEGIE MELLON"
				+ "\nCASE WESTERN"
				+ "\nCCNY"
				+ "\nCHALMERS UNIVERSITY OF TECHNOLOGY"
				+ "\nCLARK UNIVERSITY"
				+ "\nCLARKSON UNIVERSITY"
				+ "\nCOLGATE"
				+ "\nCOLLEGE OF NEWROCHELLE"
				+ "\nCOLORADO COLLEGE"
				+ "\nCOLORADO SCHOOL OF MINES"
				+ "\nCOLUMBIA"
				+ "\nCONNECTICUT COLLEGE"
				+ "\nCOOPER UNION"
				+ "\nCORNELL"
				+ "\nCORPUS CHRISTI STATE U"
				+ "\nDALLAS BAPTIST COLLEGE"
				+ "\nDARTMOUTH"
				+ "\nDEPAUL UNIVERSITY"
				+ "\nDREW"
				+ "\nEASTERN MICHIGAN"
				+ "\nEASTMAN SCHOOL OF MUSIC"
				+ "\nECOLE NATIONALE SUPERIEURE DE TELECOMMUNICATION DE PARIS"
				+ "\nECOLE POLYTECHNIQUE"
				+ "\nEMORY"
				+ "\nFLORIDA ACADEMIC UNIVERSITY"
				+ "\nFLORIDA STATE"
				+ "\nFLORIDA TECH"
				+ "\nFORDHAM"
				+ "\nGEORGE WASHINGTON"
				+ "\nGEORGETOWN"
				+ "\nGEORGIA TECH"
				+ "\nGLASSBORO STATE COLLEGE"
				+ "\nGOLDEN GATE COLLEGE"
				+ "\nGOTHENBURG UNIVERSITY"
				+ "\nHAMPSHIRE COLLEGE"
				+ "\nHARVARD"
				+ "\nHOFSTRA"
				+ "\nHOLY CROSS"
				+ "\nHUNTINGTON COLLEGE"
				+ "\nILLINOIS TECH"
				+ "\nJOHNS HOPKINS"
				+ "\nJUILLIARD"
				+ "\nLEHIGH UNIVERSITY"
				+ "\nLESLEY"
				+ "\nLEWIS AND CLARK"
				+ "\nMANHATTANVILLE COLLEGE"
				+ "\nMARIST COLLEGE"
				+ "\nMASSACHUSETTS INSTITUTE OF TECHNOLOGY"
				+ "\nMESA"
				+ "\nMICHIGAN STATE"
				+ "\nMONMOUTH COLLEGE"
				+ "\nMORGAN STATE"
				+ "\nMOUNT HOLYOKE"
				+ "\nNEW JERSEY TECH"
				+ "\nNEW YORK UNIVERSITY"
				+ "\nNEWENGLAND COLLEGE"
				+ "\nNEWJERSEY TECH"
				+ "\nNEWYORK IT"
				+ "\nNICHOLLS STATE"
				+ "\nNORTH CAROLINA STATE UNIVERSITY"
				+ "\nNORTHWESTERN"
				+ "\nNOTRE DAME"
				+ "\nOBERLIN"
				+ "\nOHIO STATE"
				+ "\nOKLAHOMA STATE UNIVERSITY"
				+ "\nORAL ROBERTS UNIVERSITY"
				+ "\nOREGON INSTITUTE OF TECHNOLOGY"
				+ "\nOREGON STATE"
				+ "\nPENN STATE"
				+ "\nPOLYTECHNIC INSTITUTE OF NEWYORK"
				+ "\nPRATT"
				+ "\nPRINCETON"
				+ "\nPURDUE"
				+ "\nQUEENS"
				+ "\nREED"
				+ "\nRENSSELAER"
				+ "\nRICE"
				+ "\nROCHESTER TECH"
				+ "\nRUTGERS"
				+ "\nSAINT ELIZABETHS"
				+ "\nSAM HOUSTON STATE UNIVERSITY"
				+ "\nSAN JOSE STATE"
				+ "\nSETON HALL"
				+ "\nSMITH"
				+ "\nST JOHNS UNIVERSITY"
				+ "\nSTANFORD"
				+ "\nSTEVENS"
				+ "\nSUFFOLK COMMUNITY COLLEGE"
				+ "\nSUNY ALBANY"
				+ "\nSUNY BINGHAMTON"
				+ "\nSUNY BUFFALO"
				+ "\nSUNY PLATTSBURGH"
				+ "\nSUNY PURCHASE"
				+ "\nSUNY STONY BROOK"
				+ "\nSWARTHMORE"
				+ "\nSYRACUSE"
				+ "\nTEMPLE"
				+ "\nTEXAS A&M"
				+ "\nTEXAS CHRISTIAN UNIVERSITY"
				+ "\nTOURO"
				+ "\nTRINITY COLLEGE"
				+ "\nTUFTS"
				+ "\nTULANE"
				+ "\nUNIVERSITE SAINT JOSEPH"
				+ "\nUNIVERSITY OF ALABAMA"
				+ "\nUNIVERSITY OF BRIDGEPORT"
				+ "\nUNIVERSITY OF CALIFORNIA BERKELEY"
				+ "\nUNIVERSITY OF CALIFORNIA DAVIS"
				+ "\nUNIVERSITY OF CALIFORNIA LOS ANGELES"
				+ "\nUNIVERSITY OF CALIFORNIA SAN DIEGO"
				+ "\nUNIVERSITY OF CALIFORNIA SANTA CRUZ"
				+ "\nUNIVERSITY OF CHICAGO"
				+ "\nUNIVERSITY OF COLORADO"
				+ "\nUNIVERSITY OF DENVER"
				+ "\nUNIVERSITY OF EVANSVILLE"
				+ "\nUNIVERSITY OF GEORGIA"
				+ "\nUNIVERSITY OF HARTFORD"
				+ "\nUNIVERSITY OF KANSAS"
				+ "\nUNIVERSITY OF LOWELL"
				+ "\nUNIVERSITY OF MAINE"
				+ "\nUNIVERSITY OF MARYLAND"
				+ "\nUNIVERSITY OF MASSACHUSETTS AMHERST"
				+ "\nUNIVERSITY OF MICHIGAN"
				+ "\nUNIVERSITY OF MINNESOTA"
				+ "\nUNIVERSITY OF MISSISSIPPI"
				+ "\nUNIVERSITY OF MISSOURI"
				+ "\nUNIVERSITY OF MONTANA"
				+ "\nUNIVERSITY OF NORTHCAROLINA"
				+ "\nUNIVERSITY OF NOTRE DAME"
				+ "\nUNIVERSITY OF OKLAHOMA"
				+ "\nUNIVERSITY OF OREGON"
				+ "\nUNIVERSITY OF PENNSYLVANIA"
				+ "\nUNIVERSITY OF PITTSBURGH"
				+ "\nUNIVERSITY OF PORTLAND"
				+ "\nUNIVERSITY OF PUGET SOUND"
				+ "\nUNIVERSITY OF ROCHESTER"
				+ "\nUNIVERSITY OF SAN FRANCISCO"
				+ "\nUNIVERSITY OF SOUTH DAKOTA"
				+ "\nUNIVERSITY OF SOUTHERN CALIFORNIA"
				+ "\nUNIVERSITY OF TEXAS"
				+ "\nUNIVERSITY OF THE DISTRICT OF COLUMBIA"
				+ "\nUNIVERSITY OF THE PACIFIC"
				+ "\nUNIVERSITY OF THE SOUTH"
				+ "\nUNIVERSITY OF TOLEDO"
				+ "\nUNIVERSITY OF TULSA"
				+ "\nUNIVERSITY OF VIRGINIA"
				+ "\nUNIVERSITY OF WASHINGTON"
				+ "\nUNIVERSITY WEST VIRGINIA"
				+ "\nVANDERBILT"
				+ "\nVASSAR"
				+ "\nVILLANOVA"
				+ "\nWALLA WALLA COLLEGE"
				+ "\nWASHINGTON AND LEE"
				+ "\nWAYNE STATE COLLEGE"
				+ "\nWESLEYAN"
				+ "\nWILLIAM PATERSON COLLEGE"
				+ "\nWORCESTER"
				+ "\nYALE"
				+ "\nYANKTOWN COLLEGE";
		assertTrue(schools.equals(output1));
	}
	
	/*
	 * View School Test
	 * 	test to make sure admin UI output is what it should be
	 */
	@Test
	public void testUC16(){
		adminUI.viewSchool("AUGSBURG");
		String output1 = outContent.toString().trim();
		System.setOut(null);
		assertTrue(output1.equals(dbc.getSchool("AUGSBURG").toString()));
	}
	
	/*
	 * Edit School Test
	 * 	checks to see if the school is changed
	 */
	@Test
	public void testUC17(){
		adminUI.addSchool("Weird1", "Alaska", "Fairbanks", "PRIVATE", 200, .9, 600, 600, 100, .9, 5, 1, 1, 5, 5, 5);
		assertTrue(adminUI.editSchool("Weird1", "Alaska", "Fairbanks", "PRIVATE", 300, .9, 600, 600, 100, .9, 5, 1, 1, 5, 5, 5));
		assertTrue(dbc.getSchool("Weird1").getNumOfStudents()==300);
		dbc.removeSchool("Weird1");
	}
	
	/*
	 * Add School Test
	 * 	checks to see if the school has been added
	 */
	@Test
	public void testUC18(){
		assertTrue(adminUI.addSchool("Weird1", "Alaska", "Fairbanks", "PRIVATE", 200, .9, 600, 600, 100, .9, 5, 1, 1, 5, 5, 5));
		assertTrue(dbc.getSchool("Weird1").getNumOfStudents()==200);
		dbc.removeSchool("Weird1");

	}
	
	/*
	 * Logout User
	 * 	tests to see if a user can log out
	 */
	@Test
	public void testUC19(){
		assertTrue(lc.studentLogout(uName));
	}
	
	/*
	 * Login Fail wrong Password
	 * 	tests to see if entering a wrong password
	 * 	fails the login
	 */
	@Test
	public void testUC20(){
		assertFalse(loginUI.logon("nadmin", "pass", true));
	}
	
	/*
	 * Edit School Fails for out of bounds params
	 * 	makes sure that you cannot edit a school crazily
	 */
	@Test
	public void testUC21(){
		adminUI.addSchool("Weird1", "Alaska", "Fairbanks", "PRIVATE", 200, .9, 600, 600, 100, .9, 5, 1, 1, 5, 5, 5);
		assertFalse(adminUI.editSchool("Weird1", "Alaska", "Fairbanks", "PRIVATE", 200, .9, 600, 600, 100, .9, 5, 1, 1, 10, 5, 5));
		dbc.removeSchool("Weird1");
	}
	
	/*
	 * Test add school fails with wrong params
	 * 	makes sure you cannot add a school with bad params
	 */
	@Test
	public void testUC22(){
		assertFalse(adminUI.addSchool("Weird1", "Alaska", "Fairbanks", "PRIVATE", 200, .9, 600, 600, 100, .9, 5, 1, 1, 10, 5, 5));
		dbc.removeSchool("Weird1");
	}
	
	/*
	 * Test Edit user fails for wrong params
	 * 	makes sure that the user isn't changed if the status isn't valid
	 */
	@Test
	public void testUC23(){
		assertFalse(adminUI.editUser(uName, fName, lName, pWord, type, 'f'));
	}
	
	/*
	 * Test Add User Fails
	 * 	makes sure you cannot add a user who is already in the database
	 */
	@Test
	public void testUC24(){
		assertFalse(adminUI.addUser(uName, fName, lName, pWord, type, status));

	}
	
	/*
	 * Test Login Fails for Wrong User Name
	 * 	makes sure you can't log in with wrong username
	 */
	@Test
	public void testUC25(){
		assertFalse(loginUI.logon("admin", "admin",true));
	}
	

}
